#!/bin/sh

CYAN='\033[1;36m'
PURPLE='\033[1;35m'
BLUE='\033[1;34m'
YELLOW='\033][1;33m'
GREEN='\033[1;32m'
RED='\033[1;31m'
NC='\033[0m'

if [ ! -d codacy-plugins-test ]; then
  printf "${CYAN}Installing test suite${NC}\n"
  git clone https://github.com/codacy/codacy-plugins-test.git && printf "${GREEN}Test suite installation successful!${NC}\n"
fi

printf "${CYAN}Building docker image${NC}\n"
docker rmi codacy-veraxx
docker build -t codacy-veraxx . && printf "${GREEN}Build successful!${NC}\n"

printf "${CYAN}Running plugin tests${NC}\n"
cd codacy-plugins-test && (sbt "run-main codacy.plugins.DockerTest all codacy-veraxx:latest" || cd ..)
